export default {
    index: 'Overview',
    'getting-started': 'Getting Started',
    'application': 'Application',
    'routing': 'Routing',
    'middleware': 'Middlewares',
    'static-files': 'Static Files',
    'template-engine': 'Template Engine',
    'request-methods': 'Request Methods',
    'response-methods': 'Response Methods',
    'http-methods': 'HTTP Methods',
    'hooks': 'Hooks',
    'advanced-features': 'Advanced Features',
    'databases': 'Databases',
    'validations': 'Validations',
    'swagger': 'Swagger UI',
    'security': 'Security',
    'logger': 'Logger',
    'support': 'Support',
}